//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaDemo.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class contatosAgenda
    {
        public int codContato { get; set; }
        public string NomeContato { get; set; }
        public string EnderecoContato { get; set; }
        public string TelefonesContato { get; set; }
        public string CelularContato { get; set; }
        public string EmailContato { get; set; }
        public string LinkedinContato { get; set; }
        public string CepContato { get; set; }
        public string PesquisaContato { get; set; }
        public Nullable<System.DateTime> DataNascimentoContato { get; set; }
        public string UFContato { get; set; }
        public string CidadeContato { get; set; }
    }
}
